// // import { Geist, Geist_Mono } from "next/font/google";
// import { Manrope } from "next/font/google";
// import "../styles/globals.css";

// const manrope = Manrope({
//   subsets: ["latin"],
//   weight: ["400", "600", "700"], // જે weight જોઈએ તે
//   variable: "--font-manrope",
// });

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en"  className={`${manrope.variable}`}>
//       {/* <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body> */}


//       <head>
//         <link href="https://api.fontshare.com/css?f[]=satoshi@400,500,700&display=swap" rel="stylesheet" />
//       </head>
//       <body className="antialiased font-manrope">
//         {children}
//       </body>
//     </html>
//   );
// }



import Header from "@/components/Header/Header";
import "../styles/globals.css";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
          <link
            href="https://api.fontshare.com/css?f[]=satoshi@400,500,700&display=swap"
            rel="stylesheet"
          />
          <link
            href="https://api.fontshare.com/css?f[]=manrope@400,500,700&display=swap"
            rel="stylesheet"
          />
        </head>
      <body className="antialiased">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}


